### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 1750585724** [spaceml-org/STARCOP#2]
Does your dataset which you had publish contain the methane leakage?

**Comment by previtus** [comment]
Hi,
Thank you for your interest in our dataset.
Yes, this dataset contains labels (labels with ground truth annotation for the semantic segmentation task) which marks the Methane plume information. Please see the third column of the visualisations in https://github.com/spaceml-org/STARCOP/blob/main/notebooks/dataset_exploration.ipynb

Best,
Vit

**Comment by 1750585724** [comment]
Hi,
Thank you for your reply!
This dataset contains '.csv' files, which contains qplume. So, i want to know is this respresenting the methane plume leakage?

**Comment by previtus** [comment]
Hi,
The qplume value in the csvs are the quantified plume emission rates of each of the plumes (in kg/h). They are reused from the annotation provided by Cusworth, D. H. et al. 2021 - more details about how this was computed can be found at https://pubs.acs.org/doi/10.1021/acs.estlett.1c00173 under the _"Section S1.2. Emission estimate from AVIRIS-NG/GAO"_ in the supplementary info (directly at https://pubs.acs.org/doi/suppl/10.1021/acs.estlett.1c00173/suppl_file/ez1c00173_si_003.pdf).
Please also note that we have manually adjusted the semantic segmentation labels - see for example Figure 3 in our paper at https://www.nature.com/articles/s41598-023-44918-6. The "qplume" value hasn't been adjusted though.

Hope this helps,
Vit
