### ISSUE TITLE
multispectral (WorldView-3) data

### ISSUE THREAD

**Issue by yaoyuan10475** [spaceml-org/STARCOP#4]
Hello, thank you for your work. I did not find the "ratio_wv3_B7_B5_varon21_sum_c_out", "ratio_wv3_B8_B5_varon21_sum_c_out" and "ratio_wv3_B7_B7MLR_SanchezGarcia22_sum_c_out" files in the dataset. I would like to ask if multispectral (WorldView-3) data is disclosed in the data set. Or maybe I didn't find it?

**Comment by previtus** [comment]
Hi,
These products get calculated from the source data (for WV3 these are _TOA_WV3_SWIR1.tif_ to _TOA_WV3_SWIR8.tif_ all available on the Zenodo page) with codes from https://github.com/spaceml-org/STARCOP/blob/main/starcop/data/feature_extration.py.
Just answering this if someone else has similar question.

Best,
Vit
