### ISSUE TITLE
Channels of AVIRIS-NG original data

### ISSUE THREAD

**Issue by yaoyuan10475** [spaceml-org/STARCOP#5]
Hello dear author, very good work. I found that in the paper "MethaneMapper: Spectral Absorption aware Hyperspectral Transformer for Methane Detection", the original data of AVIRIS-NG is 432 channels, but in your article it is 425 channels, as shown in Figure 5. So I wonder how many channels the AVIRIS-NG really has?

**Comment by previtus** [comment]
Hi,
You can check for yourself with some of the data from: https://avng.jpl.nasa.gov/avng/y19_data/

Looking for example at the .hdr file inside ang20190624t214359.tar.gz (one of the smaller ones, 1.2GB) it's 425 as we said in the article - but there may be some small changes with different flight campaigns. If so, it would be important to match them according to the wavelengths. 

Best,
Vit
